version: '3.1'
services:

  # first
  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    container_name: zoo1
    privileged: true
    ports: # 端口
      - 2181:2181
    volumes: # 挂载数据卷
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog 
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1 # 节点ID
      ZOO_PORT: 2181 # zookeeper端口号
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 # zookeeper节点列表
    networks:
      mynetwork:
        ipv4_address: 172.16.1.4
  exp1:
    image: dabealu/zookeeper-exporter
    ports:
      - 9141:9141
    command: --zk-hosts="zoo1:2181"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.7


  # second
  zoo2:
    image: zookeeper:3.4
    hostname: zoo2
    container_name: zoo2
    privileged: true
    ports: # 端口
      - 2182:2181
    volumes: # 挂载数据卷
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog 
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2 # 节点ID
      ZOO_PORT: 2181 # zookeeper端口号
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 # zookeeper节点列表
    networks:
      mynetwork:
        ipv4_address: 172.16.1.5
  exp2:
    image: dabealu/zookeeper-exporter
    ports:
      - 9142:9141
    command: --zk-hosts="zoo2:2181"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.8

  # third
  zoo3:
    image: zookeeper:3.4
    hostname: zoo3
    container_name: zoo3
    privileged: true
    ports: # 端口
      - 2183:2181
    volumes: # 挂载数据卷
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog 
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3 # 节点ID
      ZOO_PORT: 2181 # zookeeper端口号
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 # zookeeper节点列表
    networks:
      mynetwork:
        ipv4_address: 172.16.1.6
  exp3:
    image: dabealu/zookeeper-exporter
    ports:
      - 9143:9141
    command: --zk-hosts="zoo3:2181"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.9

  # multitarget
  exp123:
    image: dabealu/zookeeper-exporter
    # build:
    #   context: .
    ports:
      - 9144:9141
    command: --zk-hosts="zoo1:2181,zoo2:2181,zoo3:2181" --timeout=5
    networks:
      mynetwork:
        ipv4_address: 172.16.1.21
networks:
 mynetwork:
  external:
   name: mynetwork

