version: '3.1'
services:

  # first
  zoo1:
    image: zookeeper:3.6
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./conf/zoo.cfg.1:/conf/zoo.cfg
    networks:
      mynetwork:
        ipv4_address: 172.16.1.4
  exp1:
    image: dabealu/zookeeper-exporter
    ports:
      - 9141:9141
    command: --zk-hosts="zoo1:2181"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.7


  # second
  zoo2:
    image: zookeeper:3.6
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
    volumes:
      - ./conf/zoo.cfg.2:/conf/zoo.cfg
    networks:
      mynetwork:
        ipv4_address: 172.16.1.5
  exp2:
    image: dabealu/zookeeper-exporter
    ports:
      - 9142:9141
    command: --zk-hosts="zoo2:2181"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.8

  # third
  zoo3:
    ##### Uncomment block below and comment 'image' parameter in order to test timeout
    # build:
    #   context: zoo-timeout
    # privileged: true  # Needed for iptables drop rule to work in custom entrypoint script
    ##### End
    image: zookeeper:3.6
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./conf/zoo.cfg.3:/conf/zoo.cfg
    networks:
      mynetwork:
        ipv4_address: 172.16.1.6
  exp3:
    image: dabealu/zookeeper-exporter
    ports:
      - 9143:9141
    command: --zk-hosts="zoo3:2181" --timeout=5
    networks:
      mynetwork:
        ipv4_address: 172.16.1.9

  # multitarget
  exp123:
    image: dabealu/zookeeper-exporter
    # build:
    #   context: .
    ports:
      - 9144:9141
    command: --zk-hosts="zoo1:2181,zoo2:2181,zoo3:2181" --timeout=5
    networks:
      mynetwork:
        ipv4_address: 172.16.1.21
networks:
 mynetwork:
  external:
   name: mynetwork

